import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar';
import Login from './Login';
import styles from '../styles/Home.module.css';

import { getProviders, getSession, useSession } from "next-auth/react";

export default function Home({ trendingResults, followResults, providers }) {

  // const { session } = useSession();
  const { data: session } = useSession();

  console.log("session", session);

  if(!session){
    return <Login providers={providers} />
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-[#000] container mx-auto h-screen flex items-start justify-between max-w-[1500px]'>
        <Sidebar />
        <Feed />
        {/* <h2 className='text-white'>Widgets</h2> */}
        {/* { session.user.name } */}
       
        {/* Modal */}
      </main>
  
    </div>
  )
}

export async function getServerSideProps(context){

  const responseTrending = await fetch("https://www.jsonkeeper.com/b/NKEV");
  const trendingResults = await responseTrending.json();

  const responseFollowes =  await fetch("https://www.jsonkeeper.com/b/WWMJ");
  const followResults = await responseFollowes.json();

  const providers = await getProviders();
  // const session = await getSession(context);

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      // session
    }
  }
}
